name: Auto Deploy Report

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "🔄 Checkout code"
        uses: actions/checkout@v4

      - name: "🐹 Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: "🔧 Setup environment variables from secrets"
        env:
          SECRETS_CONTEXT: ${{ toJSON(secrets) }}
        run: |
          echo "Setting up environment variables from GitHub secrets..."
          echo "$SECRETS_CONTEXT" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
          echo "Environment variables configured from secrets"

      - name: "🏗️ Build and run PongHub"
        run: |
          mkdir -p bin data
          git clone --branch gh-pages https://github.com/${{ github.repository }}.git || true
          if [ -f ponghub/ponghub_log.json ]; then
            cp ponghub/ponghub_log.json data/ponghub_log.json
          else
            echo "New installation, no previous data found."
          fi
          make run || true

      - name: "📦 Prepare publish directory"
        run: |
          mkdir -p publish/static
          cp -r data/* publish/
          cp -r static/* publish/static/
          if [ -f CNAME ]; then
            cp CNAME publish/
          else
            echo "No CNAME file found."
          fi
          touch publish/.nojekyll

      - name: "🚀 Deploy to GitHub Pages"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: publish
          git-config-name: github-pages-deploy-action
          git-config-email: noreply@github.com

      - name: "⚠️ Handle Service Notifications"
        run: |
          if [ -f data/notify.txt ] && [ -s data/notify.txt ]; then
            echo "Service issues detected:"
            cat data/notify.txt
            echo "Service issues have been reported through the configured notification channels."
            echo "If no notifications were received, please check your notification configuration in config.yaml"
            if [ "$PONGHUB_HAS_ALERTS" = "true" ]; then
              echo ""
              echo "🚨 DEFAULT NOTIFICATION: GitHub Actions failure triggered as notification method"
              echo "This workflow is failing intentionally to alert you of service issues."
              echo "To receive notifications through other channels, configure them in config.yaml"
              echo ""
              exit 1
            fi
          else
            echo "No service issues detected."
          fi